name: rp2 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/rp2/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'micropython repo'  # test build with space in path
    steps:
    - uses: actions/checkout@v4
      with:
        path: 'micropython repo'
    - name: Install packages
      run: source tools/ci.sh && ci_rp2_setup
    - name: Build
      run: source tools/ci.sh && ci_rp2_build
    - name: Archive PICO firmware
      uses: actions/upload-artifact@v4
      with:
        name: microlite-rp2-pico-firmware
        path: |
          micropython-tflite/micropython/build-RPI_PICO_W/firmware.elf
          micropython-tflite/micropython/build-RPI_PICO_W/firmware.bin
          micropython-tflite/micropython/build-RPI_PICO_W/firmware.dis
          micropython-tflite/micropython/build-RPI_PICO_W/firmware.elf.map
          micropython-tflite/micropython/build-RPI_PICO_W/firmware.hex
          micropython-tflite/micropython/build-RPI_PICO_W/firmware.uf2